import dice
import restrictions
from characters import abilityscores
from characters import specialabilities
from characters.classes import Level, LevelTable
from characters.classes.base import CharacterClass
from characters.savingthrows import SavingThrowSet
from items import armor
from spells import SpellSlotSet


class Thief(CharacterClass):
    name = "Thief"
    restriction_set = restrictions.RestrictionSet(
        ability_score=restrictions.AbilityScoreRestrictionSet(
            minimum_set=abilityscores.AbilityScoreSet(dexterity=9)
        ),
        armor=restrictions.ArmorRestrictionSet(
            included=(armor.types.Clothing, armor.types.LightArmor)
        )
    )
    special_abilities = specialabilities.SpecialAbilitySet(
        special_abilities=(
            specialabilities.ClimbWalls,
            specialabilities.Hide,
            specialabilities.Listen,
            specialabilities.MoveSilently,
            specialabilities.OpenLock,
            specialabilities.RemoveTraps,
            specialabilities.PickPockets,
        )
    )
    level_table = LevelTable(
        levels=(
            Level(
                value=1,
                attack_bonus=1,
                experience_required=0,
                hit_dice=dice.D4(1),
                saving_throws_set=SavingThrowSet(
                    death_poison=13,
                    dragon_breath=16,
                    paralysis_stone=13,
                    spells=15,
                    wands=14
                )
            ),
            Level(
                value=2,
                attack_bonus=1,
                experience_required=1500,
                hit_dice=dice.D4(2),
                saving_throws_set=SavingThrowSet(
                    death_poison=12,
                    dragon_breath=15,
                    paralysis_stone=12,
                    spells=14,
                    wands=14
                )
            ),
            Level(
                value=3,
                attack_bonus=2,
                experience_required=3000,
                hit_dice=dice.D4(3),
                saving_throws_set=SavingThrowSet(
                    death_poison=12,
                    dragon_breath=15,
                    paralysis_stone=12,
                    spells=14,
                    wands=14
                )
            ),
            Level(
                value=4,
                attack_bonus=2,
                experience_required=6000,
                hit_dice=dice.D4(4),
                saving_throws_set=SavingThrowSet(
                    death_poison=11,
                    dragon_breath=14,
                    paralysis_stone=12,
                    spells=13,
                    wands=13
                )
            ),
            Level(
                value=5,
                attack_bonus=3,
                experience_required=12000,
                hit_dice=dice.D4(5),
                saving_throws_set=SavingThrowSet(
                    death_poison=11,
                    dragon_breath=14,
                    paralysis_stone=12,
                    spells=13,
                    wands=13
                )
            ),
            Level(
                value=6,
                attack_bonus=3,
                experience_required=24000,
                hit_dice=dice.D4(6),
                saving_throws_set=SavingThrowSet(
                    death_poison=11,
                    dragon_breath=13,
                    paralysis_stone=11,
                    spells=13,
                    wands=13
                )
            ),
            Level(
                value=7,
                attack_bonus=4,
                experience_required=48000,
                hit_dice=dice.D4(7),
                saving_throws_set=SavingThrowSet(
                    death_poison=11,
                    dragon_breath=13,
                    paralysis_stone=11,
                    spells=13,
                    wands=13
                )
            ),
            Level(
                value=8,
                attack_bonus=4,
                experience_required=90000,
                hit_dice=dice.D4(8),
                saving_throws_set=SavingThrowSet(
                    death_poison=10,
                    dragon_breath=12,
                    paralysis_stone=11,
                    spells=12,
                    wands=12
                )
            ),
            Level(
                value=9,
                attack_bonus=5,
                experience_required=180000,
                hit_dice=dice.D4(9),
                saving_throws_set=SavingThrowSet(
                    death_poison=10,
                    dragon_breath=12,
                    paralysis_stone=11,
                    spells=12,
                    wands=12
                )
            ),
            Level(
                value=10,
                attack_bonus=5,
                experience_required=270000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=2,
                saving_throws_set=SavingThrowSet(
                    death_poison=9,
                    dragon_breath=11,
                    paralysis_stone=10,
                    spells=11,
                    wands=12
                )
            ),
            Level(
                value=11,
                attack_bonus=5,
                experience_required=360000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=4,
                saving_throws_set=SavingThrowSet(
                    death_poison=9,
                    dragon_breath=11,
                    paralysis_stone=10,
                    spells=11,
                    wands=12
                )
            ),
            Level(
                value=12,
                attack_bonus=6,
                experience_required=450000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=6,
                saving_throws_set=SavingThrowSet(
                    death_poison=9,
                    dragon_breath=10,
                    paralysis_stone=10,
                    spells=11,
                    wands=10
                )
            ),
            Level(
                value=13,
                attack_bonus=6,
                experience_required=540000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=8,
                saving_throws_set=SavingThrowSet(
                    death_poison=9,
                    dragon_breath=10,
                    paralysis_stone=10,
                    spells=11,
                    wands=10
                )
            ),
            Level(
                value=14,
                attack_bonus=6,
                experience_required=630000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=10,
                saving_throws_set=SavingThrowSet(
                    death_poison=8,
                    dragon_breath=9,
                    paralysis_stone=9,
                    spells=10,
                    wands=10
                )
            ),
            Level(
                value=15,
                attack_bonus=7,
                experience_required=720000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=12,
                saving_throws_set=SavingThrowSet(
                    death_poison=8,
                    dragon_breath=9,
                    paralysis_stone=9,
                    spells=10,
                    wands=10
                )
            ),
            Level(
                value=16,
                attack_bonus=7,
                experience_required=810000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=14,
                saving_throws_set=SavingThrowSet(
                    death_poison=7,
                    dragon_breath=8,
                    paralysis_stone=9,
                    spells=9,
                    wands=9
                )
            ),
            Level(
                value=17,
                attack_bonus=7,
                experience_required=900000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=16,
                saving_throws_set=SavingThrowSet(
                    death_poison=7,
                    dragon_breath=8,
                    paralysis_stone=9,
                    spells=9,
                    wands=9
                )
            ),
            Level(
                value=18,
                attack_bonus=8,
                experience_required=990000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=18,
                saving_throws_set=SavingThrowSet(
                    death_poison=7,
                    dragon_breath=7,
                    paralysis_stone=8,
                    spells=9,
                    wands=9
                )
            ),
            Level(
                value=19,
                attack_bonus=8,
                experience_required=1080000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=20,
                saving_throws_set=SavingThrowSet(
                    death_poison=7,
                    dragon_breath=7,
                    paralysis_stone=8,
                    spells=9,
                    wands=9
                )
            ),
            Level(
                value=20,
                attack_bonus=8,
                experience_required=1170000,
                hit_dice=dice.D4(9),
                hit_dice_flat_bonus=22,
                saving_throws_set=SavingThrowSet(
                    death_poison=6,
                    dragon_breath=6,
                    paralysis_stone=8,
                    spells=8,
                    wands=8
                )
            )
        )
    )
